version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb_server
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    restart: always

volumes:
  redis_data:
  chroma_data:

